* work-in-progress (WIP, limit 5)
Let nag communicate with interact sessions.
Read current interaction content with nag and (possibley) put it into context.
Add (maybe?) ghostcode interaction as a nagsource.
Create inter process communication for  ghostcode processes (ugh).
Make nag command send message to current itneract session on certain user requests.
Maybe give nag command more context.
Create emacsbuffer nag source.
Create current emacs buffer nag source.
Write emacs.py function to get buffer around point.
Put current emacs buffer with +/- 20 lines around point into nag context.
Fix nag htt psource not being very sensitive to content (needs testing).
Add take_a_break IdleTask to idle worker.
Think about implementing a lock around dumping history.
Yeah, refactor history saving (_dump_interaction_history)
find out why sometimes titles aren't being assigned
RAG on past itneractions.

Make audio input be able to shup up (as in, take a break) nag command.
* todo
** general
Narrow the type of Action in actions_from_response_part (since it's a response it must be a query action)
Remove branching code in make_prompt_worker_coder_request after original_action type has been narrowed
Make recovery an action.
Fix newline on some commands.
Fix glob patterns when adding/removing context files
Add simple check script option that worker runs and passes on to coder on fail
Ability to add server log or other output logs (this is technically already possible but can we make it more explicit).
Make it so that pasted interaction IDs cause a rag lookup.
make unique_ids into a newtype (e.g. InteractionID)
Simulate file edits and show diffs
Figure out a way to run tests/run the program so AI can get feedback and see errors
Add doc comment injections to yaml config files.
refactor init and saving of project
Audio input support for small queries ("hey ghostcode, what was the parser class called in this project?")
Investigate proper deployment (conda, docker, getting llama.cpp, downloading models from huggingface).
More user friendly setup during init for various backends (ask for API keys etc).
Status command (not sure what it should even do yet).
git integration.
More useful CLI commands.
Keep main command executiong from crashing catastrophically (wrap in try and exit gracefully).
* emacs integration
Investigate autocomplete
get list of buffers that are also in context
get list of buffers that are under current project root
Add opened emacs buffers that are under project root automatically to context (with config option to disable)
Show diffs in emacs
function to show arbitrary text to user in a buffer
special buffer to share extra context
investigate other uses
** CLI
Redo the entire action_queue printing stuff properly
Add /help command.
** testing
Properly test worker recovery.
Test shell command actions.
Debug/test raw prompts.
** coder
Investigate wether structured output degrades performance.
** worker
Add context expansion/contraction by worker
** tests
Write tests for the virtual terminal
* about this file
Todo list that's structured like a Canban board.
One line is one todo-item.
Single asterisk (org-mode) headings indicate canban columns (except this 'about this file' heading). These are WIP, Todo, and Done.
 - WIP: Contains items currently being worked on. Work may include research for vague items, that generate more items for the todo list.
 - todo: Contains items that may be worked on in the future. These can be very specific, or vague and general. To be worked on, an item moves from this list into the WIP list. This list also contains 2 asterisk sub-headings to structure it. A single todo item is still a plaintext line, though.
 - done: Contains todo items that have been finished. Also known as "brag list". Somewhat pointless but can be useful to get an overview of the projects history.
* done
Create function to reliably replace or create code based on CoderResponsePart (possibly using worker).
Integrate worker into interact mode.
Add clearance types.
Add basic confirmation dialog.
Create virtual shell
Create action that let's worker ask coder for adjustment.
Give actions short string representation to be used at various points in the CLI interface.
Fix broken recovery.
Handle code file edit cases of inadequate levenshtein distance.
Make a show_log method for program.
Fix log file not being created when logging is set to stderr.
Create basic testing framework (/tests folder and scripts).
Create log command to view past interactions.
add talk command
Have worker make title for interactions
Refactor ghostcoder querying from interact subcommand to action queue.
add proper SlashCommand type for slash (like "/quit") commands in interact mode.
emacs integration (use server and emacslisp generation with "emacs -e").
Add ActionShellCommand to execute_action match case.
Create prompt for worker waiting on shell command
Create worker routing
Refactor prompt creation into prompts.py
Create /talk and /interact commands to switch mid session
make proper multiline mode utility function (discarded - I like the logic in _loop_interact)
Improve file edit displays
Implement context altering.
Add style.md.
Make context file list sorted.
Fix not being able to remove no longer existing files from context files
Look into locking .ghostcode while interaction is in progress.
Add interaction locking.
Add interaction folders/groupings.
Make interaction folders/groupings default to be identical with git branches.
Add -b,--branch parameter to interaction commands to automatically checkout a git branch
create async worker process
Add summarization to idle worker tasks.
Implement nag command.
Make nag command work well with mypy.
Make nag command speak with tts.
Nag personalities.
Make nag sources use a hash in nagresult if there is a problem.
Make nag command check hash and not repeat same problem (or only twice).
Nag with audio input.
Make nag command notice that a problem has been fixed.
Fix nag command with audio input not quitting
Make nag command not save project.
